### ISSUE TITLE
size problem

### ISSUE THREAD

**Issue by matiasmolinas** [pruthvikar/SensorTag-Fusion#1]
When I try to compile the project I'm getting this error:

Error[e104]: Failed to fit all segments into specified ranges. Problem discovered in segment BANKED_CODE. Unable to place 82 block(s) (0x1c689 byte(s) total) in  
0x1b587 byte(s) of memory. The problem occurred while processing the segment placement command  
"-P(CODE)BANKED_CODE=_CODE_BEG-_CODE_END,_BANK1_BEG-_BANK1_END,_BANK2_BEG-_BANK2_END,_BANK3_BEG-_BANK3_END,_BANK4_BEG-_ 
BANK4_END", where at the moment of placement the available memory ranges were  
"CODE:7654-7ff7,CODE:18000-1ffff,CODE:28000-2ffff,CODE:38000-3ffff,CODE:4841d-4afff" 
Error while running Linker

**Comment by ebadier** [comment]
Hi Matias,

I tried to compile SensorTag-Fusion too, using IAR Embedded workbench 9.20.1.
When I try to compile the project with configurations CC2541DK-Sensor-OAD-ImgA & CC2541DK-Sensor-OAD-ImgB, I get this error message:

Error[e16]: Segment ISTACK (size: 0xc0 align: 0) is too long for segment definition. At least 0xe more bytes needed. The problem occurred while processing the  
segment placement command "-Z(IDATA)ISTACK+_IDATA_STACK_SIZE#_IDATA_BEG-_IDATA_END", where at the moment of placement the available memory  
ranges were "IDATA:4e-ff" 
   Reserved ranges relevant to this placement: 
   IDATA:a-1f           VREG 
   IDATA:21-40          VREG 
   IDATA:41-42          XSP 
   IDATA:43-43          DATA_I 
   IDATA:44-4b          DATA_Z 
   IDATA:4c-4d          IDATA_Z 
   IDATA:4e-ff          ISTACK 
   BIT:0-7              BREG 
   BIT:80-97            SFR_AN 
   BIT:a0-af            SFR_AN 
   BIT:b8-c7            SFR_AN 
   BIT:e8-ef            SFR_AN

It seems to be similar to your problem, but I don't know how to solve it too.

Did you find any solution now ?

**Comment by pruthvikar** [comment]
Hi ebadier,

When I was working on this project, I had built and test the services separately and combined them at the end. I'd suggest you comment out the services that you aren't using until the compilation works.

**Comment by ebadier** [comment]
Thanks pruthvikar !
I commented out humidity/bar/irtemp and now the firmware fits in memory :+1:
