### ISSUE TITLE
Fusion 

### ISSUE THREAD

**Issue by tasospet** [pruthvikar/SensorTag-Fusion#2]
Hi,I have a question. The fusion you said runs in 250 Hz frequency but in the madwick algorithm you set the sampleFreq in 512 Hz. Why you do that ? I don't quite understand...Thanks in advance

**Comment by pruthvikar** [comment]
Thanks, I've just fixed this now 25544998dc34ea4f5f3efccd51a897eb455a82c6

**Comment by tasospet** [comment]
And just another question ..you run it through the timer osal? every 4 msec?
Thanks!
